elasticsearch:
  image: akaimo/elasticsearch:2.3.3
  ports:
    - "9200:9200"
    - "9300:9300"
  container_name: elasticsearch
  hostname: elasticsearch
kibana:
  image: akaimo/kibana:4.5.1
  ports:
    - "5601:5601"
  container_name: kibana
  links: 
    - elasticsearch
#   command: http://elasticsearch:9200
