elasticsearch:
  build: ./elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  container_name: elasticsearch
  hostname: elasticsearch
kibana:
  build: ./kibana
  ports:
    - "5601:5601"
  container_name: kibana
  links: 
    - elasticsearch
#   command: http://elasticsearch:9200
